/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'description' : string,
  'isPast' : boolean,
  'timestamp' : Time,
  'eventType' : EventType,
}
export type EventType = { 'culturalProgram' : null } |
  { 'associationMeeting' : null } |
  { 'welfareDrive' : null };
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
}
export type MembershipType = { 'premium' : null } |
  { 'regular' : null };
export interface Notice {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : string,
  'timestamp' : Time,
  'category' : NoticeCategory,
}
export type NoticeCategory = { 'civicIssues' : null } |
  { 'meetings' : null } |
  { 'waterSupply' : null } |
  { 'general' : null };
export type PaymentType = { 'welfareFund' : null } |
  { 'maintenanceFee' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [EventType, string, string, string, boolean],
    bigint
  >,
  'createNotice' : ActorMethod<
    [NoticeCategory, string, string, string],
    bigint
  >,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteNotice' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [string, string, string]>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getLatestNotices' : ActorMethod<[bigint], Array<Notice>>,
  'getNoticesByCategory' : ActorMethod<[NoticeCategory], Array<Notice>>,
  'getPastEvents' : ActorMethod<[], Array<Event>>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string, string], bigint>,
  'submitMembershipRegistration' : ActorMethod<
    [string, string, string, string, MembershipType],
    bigint
  >,
  'submitPayment' : ActorMethod<[bigint, bigint, PaymentType, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];