/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventType = IDL.Variant({
  'culturalProgram' : IDL.Null,
  'associationMeeting' : IDL.Null,
  'welfareDrive' : IDL.Null,
});
export const NoticeCategory = IDL.Variant({
  'civicIssues' : IDL.Null,
  'meetings' : IDL.Null,
  'waterSupply' : IDL.Null,
  'general' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'timestamp' : Time,
  'category' : NoticeCategory,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'isPast' : IDL.Bool,
  'timestamp' : Time,
  'eventType' : EventType,
});
export const MembershipType = IDL.Variant({
  'premium' : IDL.Null,
  'regular' : IDL.Null,
});
export const PaymentType = IDL.Variant({
  'welfareFund' : IDL.Null,
  'maintenanceFee' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [EventType, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createNotice' : IDL.Func(
      [NoticeCategory, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Text, IDL.Text, IDL.Text], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getLatestNotices' : IDL.Func([IDL.Nat], [IDL.Vec(Notice)], ['query']),
  'getNoticesByCategory' : IDL.Func(
      [NoticeCategory],
      [IDL.Vec(Notice)],
      ['query'],
    ),
  'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeBootstrapToken' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitMembershipRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, MembershipType],
      [IDL.Nat],
      [],
    ),
  'submitPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, PaymentType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateEvent' : IDL.Func(
      [IDL.Nat, EventType, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateNotice' : IDL.Func(
      [IDL.Nat, NoticeCategory, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventType = IDL.Variant({
    'culturalProgram' : IDL.Null,
    'associationMeeting' : IDL.Null,
    'welfareDrive' : IDL.Null,
  });
  const NoticeCategory = IDL.Variant({
    'civicIssues' : IDL.Null,
    'meetings' : IDL.Null,
    'waterSupply' : IDL.Null,
    'general' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'timestamp' : Time,
    'category' : NoticeCategory,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'isPast' : IDL.Bool,
    'timestamp' : Time,
    'eventType' : EventType,
  });
  const MembershipType = IDL.Variant({
    'premium' : IDL.Null,
    'regular' : IDL.Null,
  });
  const PaymentType = IDL.Variant({
    'welfareFund' : IDL.Null,
    'maintenanceFee' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [EventType, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createNotice' : IDL.Func(
        [NoticeCategory, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Text, IDL.Text, IDL.Text], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getLatestNotices' : IDL.Func([IDL.Nat], [IDL.Vec(Notice)], ['query']),
    'getNoticesByCategory' : IDL.Func(
        [NoticeCategory],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeBootstrapToken' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitMembershipRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, MembershipType],
        [IDL.Nat],
        [],
      ),
    'submitPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateEvent' : IDL.Func(
        [IDL.Nat, EventType, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateNotice' : IDL.Func(
        [IDL.Nat, NoticeCategory, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };